=== emazzotta/morsecoder/trunk/src/main/resources/morsecode.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xsd:schema elementFormDefault="qualified" xmlns:morsecode="http://www.crumbleworks.org/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<xsd:element name="morsecode">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="morsecharacter" maxOccurs="unbounded">
					<xsd:complexType>
						<xsd:sequence>
							<xsd:element name="letter" type="xsd:string" />
							<xsd:element name="code" type="xsd:string" />
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
			</xsd:sequence>
			<xsd:attribute name="name" type="xsd:string" />
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== emazzotta/morsecoder/target/classes/xml/morsecode.xml
<?xml version="1.0" encoding="UTF-8"?>
<morsecode name="general" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="morsecode.xsd">
	<morsecharacter>
		<letter>A</letter>
		<code>.-</code>
	</morsecharacter>
	<morsecharacter>
		<letter>B</letter>
		<code>-...</code>
	</morsecharacter>
	<morsecharacter>
		<letter>C</letter>
		<code>-.-.</code>
	</morsecharacter>
	<morsecharacter>
		<letter>D</letter>
		<code>-..</code>
	</morsecharacter>
	<morsecharacter>
		<letter>E</letter>
		<code>.</code>
	</morsecharacter>
	<morsecharacter>
		<letter>F</letter>
		<code>..-.</code>
	</morsecharacter>
	<morsecharacter>
		<letter>G</letter>
		<code>--.</code>
	</morsecharacter>
	<morsecharacter>
		<letter>H</letter>
		<code>....</code>
	</morsecharacter>
	<morsecharacter>
		<letter>I</letter>
		<code>..</code>
	</morsecharacter>
	<morsecharacter>
		<letter>J</letter>
		<code>.---</code>
	</morsecharacter>
	<morsecharacter>
		<letter>K</letter>
		<code>-.-</code>
	</morsecharacter>
	<morsecharacter>
		<letter>L</letter>
		<code>.-..</code>
	</morsecharacter>
	<morsecharacter>
		<letter>M</letter>
		<code>--</code>
	</morsecharacter>
	<morsecharacter>
		<letter>N</letter>
		<code>-.</code>
	</morsecharacter>
	<morsecharacter>
		<letter>O</letter>
		<code>---</code>
	</morsecharacter>
	<morsecharacter>
		<letter>P</letter>
		<code>.--.</code>
	</morsecharacter>
	<morsecharacter>
		<letter>Q</letter>
		<code>--.-</code>
	</morsecharacter>
	<morsecharacter>
		<letter>R</letter>
		<code>.-.</code>
	</morsecharacter>
	<morsecharacter>
		<letter>S</letter>
		<code>...</code>
	</morsecharacter>
	<morsecharacter>
		<letter>T</letter>
		<code>-</code>
	</morsecharacter>
	<morsecharacter>
		<letter>U</letter>
		<code>..-</code>
	</morsecharacter>
	<morsecharacter>
		<letter>V</letter>
		<code>...-</code>
	</morsecharacter>
	<morsecharacter>
		<letter>W</letter>
		<code>.--</code>
	</morsecharacter>
	<morsecharacter>
		<letter>X</letter>
		<code>-..-</code>
	</morsecharacter>
	<morsecharacter>
		<letter>Y</letter>
		<code>-.--</code>
	</morsecharacter>
	<morsecharacter>
		<letter>Z</letter>
		<code>--..</code>
	</morsecharacter>
	
	<morsecharacter>
		<letter>0</letter>
		<code>-----</code>
	</morsecharacter>
	<morsecharacter>
		<letter>1</letter>
		<code>.----</code>
	</morsecharacter>
	<morsecharacter>
		<letter>2</letter>
		<code>..---</code>
	</morsecharacter>
	<morsecharacter>
		<letter>3</letter>
		<code>...--</code>
	</morsecharacter>
	<morsecharacter>
		<letter>4</letter>
		<code>....-</code>
	</morsecharacter>
	<morsecharacter>
		<letter>5</letter>
		<code>.....</code>
	</morsecharacter>
	<morsecharacter>
		<letter>6</letter>
		<code>-....</code>
	</morsecharacter>
	<morsecharacter>
		<letter>7</letter>
		<code>--...</code>
	</morsecharacter>
	<morsecharacter>
		<letter>8</letter>
		<code>---..</code>
	</morsecharacter>
	<morsecharacter>
		<letter>9</letter>
		<code>----.</code>
	</morsecharacter>
	
	<morsecharacter>
		<letter>.</letter>
		<code>.-.-.-</code>
	</morsecharacter>
	<morsecharacter>
		<letter> </letter>
		<code>/</code>
	</morsecharacter>
	<morsecharacter>
		<letter>,</letter>
		<code>--..--</code>
	</morsecharacter>
	<morsecharacter>
		<letter>:</letter>
		<code>---...</code>
	</morsecharacter>
	<morsecharacter>
		<letter>;</letter>
		<code>-.-.-.</code>
	</morsecharacter>
	<morsecharacter>
		<letter>?</letter>
		<code>--..--</code>
	</morsecharacter>
	<morsecharacter>
		<letter>-</letter>
		<code>-....-</code>
	</morsecharacter>
	<morsecharacter>
		<letter>_</letter>
		<code>--..-.</code>
	</morsecharacter>
	<morsecharacter>
		<letter>(</letter>
		<code>-.--.</code>
	</morsecharacter>
	<morsecharacter>
		<letter>)</letter>
		<code>-.--.-</code>
	</morsecharacter>
	<morsecharacter>
		<letter>'</letter>
		<code>.----.</code>
	</morsecharacter>
	<morsecharacter>
		<letter>=</letter>
		<code>-...-</code>
	</morsecharacter>
	<morsecharacter>
		<letter>+</letter>
		<code>.-.-.</code>
	</morsecharacter>
	<morsecharacter>
		<letter>/</letter>
		<code>-..-.</code>
	</morsecharacter>
	<morsecharacter>
		<letter>@</letter>
		<code>.--.-.</code>
	</morsecharacter>
	
	<morsecharacter>
		<letter>[AA]</letter>
		<code>.-.-</code>
	</morsecharacter>
	<morsecharacter>
		<letter>[AR]</letter>
		<code>.-.-.</code>
	</morsecharacter>
	<morsecharacter>
		<letter>[AS]</letter>
		<code>.-...</code>
	</morsecharacter>
	<morsecharacter>
		<letter>[BK]</letter>
		<code>-...-.-</code>
	</morsecharacter>
	<morsecharacter>
		<letter>[BT]</letter>
		<code>-...-</code>
	</morsecharacter>
	<morsecharacter>
		<letter>[CL]</letter>
		<code>-.-..-..</code>
	</morsecharacter>
	<morsecharacter>
		<letter>[CT]</letter>
		<code>-.-.-</code>
	</morsecharacter>
	<morsecharacter>
		<letter>[K]</letter>
		<code>-.-</code>
	</morsecharacter>
	<morsecharacter>
		<letter>[KN]</letter>
		<code>-.--.</code>
	</morsecharacter>
	<morsecharacter>
		<letter>[SK]</letter>
		<code>...-.-</code>
	</morsecharacter>
	<morsecharacter>
		<letter>[SN]</letter>
		<code>...-.</code>
	</morsecharacter>
	<morsecharacter>
		<letter>[SOS]</letter>
		<code>...---...</code>
	</morsecharacter>
</morsecode>
